sudo: false

language: java
jdk:
  - openjdk8

before_install:
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip -O /tmp/z3.zip
  - unzip /tmp/z3.zip
  - export PATH=$PATH:$PWD/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04/bin/
